title: 'Homebrew Catalog '
description: >-
  A frontend for my homebrew file server, which contains many pieces of Nintendo
  homebrew.
social_link: instagram
social_username: mochathebeardie
github_repo: hb-catalog
github_username: FieryMewtwo
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /hb-catalog
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
